config/routes.rb
def set_up_sidekiq
  require 'sidekiq/web'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      compare = ->(s1, s2) { ActiveSupport::SecurityUtils.secure_compare(s1, s2) }
      compare.call(username, ENV["SIDEKIQ_USERNAME"]) && compare.call(password, ENV["SIDEKIQ_PASSWORD"])
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

def set_up_flipper
  flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
    builder.use Rack::Auth::Basic do |username, password|
      username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
    end
  end
  mount flipper_app, at: "/flipper"
end

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_for :partner_users, controllers: { sessions: "partners/sessions", invitations: 'partners/invitations', passwords: 'partners/passwords' }
  resources :logins, only: [:new, :create], controller: "consolidated_logins"

  set_up_sidekiq
  set_up_flipper

  # Add route partners/dashboard so that we can define it as partner_user_root
  get 'partners/dashboard' => 'partners/dashboards#show', as: :partner_user_root
  namespace :partners do
    resource :dashboard, only: [:show]
    resource :help, only: [:show]
    resources :requests, only: [:show, :new, :index, :create]
    resources :individuals_requests, only: [:new, :create]
    resources :family_requests, only: [:new, :create]
    resources :users, only: [:index, :new, :create]
    resource :profile, only: [:show, :edit, :update]
    resource :approval_request, only: [:create]

    resources :children, except: [:destroy] do
      post :active
    end
    resources :families
    resources :authorized_family_members
  end

  # This is where a superadmin CRUDs all the things
  get :admin, to: "admin#dashboard"
  namespace :admin do
    get :dashboard
    resources :base_items
    resources :organizations
    resources :partners, except: %i[new create destroy]
    resources :users
    resources :barcode_items
    resources :account_requests, only: [:index]
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  scope path: ":organization_id" do
    resources :users

    # Users that are organization admins can manage the organization itself
    resource :organization, only: [:show]
    resource :organization, path: :manage, only: %i(edit update) do
      collection do
        post :invite_user
        put :deactivate_user
        put :reactivate_user
        post :resend_user_invitation
        post :promote_to_org_admin
        post :demote_to_user
      end
    end

    resources :adjustments, except: %i(edit update)
    resources :audits do
      post :finalize
    end

    namespace :reports do
      resources :ndbn_annuals, only: [:index, :show], param: :year
    end

    resources :transfers, only: %i(index create new show destroy)
    resources :storage_locations do
      collection do
        post :import_csv
        post :import_inventory
      end
      member do
        get :inventory
      end
    end

    resources :distributions do
      get :print, on: :member
      collection do
        get :schedule
        get :pickup_day
      end
      patch :picked_up, on: :member
    end

    resources :barcode_items do
      get :find, on: :collection
      get :font, on: :collection
    end
    resources :donation_sites do
      collection do
        post :import_csv
      end
    end
    resources :diaper_drive_participants, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :manufacturers, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :vendors, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :kits do
      member do
        get :allocations
        post :allocate
      end
    end

    resources :profiles, only: %i(edit update)
    resources :items do
      patch :restore, on: :member
    end
    resources :item_categories
    resources :partners do
      collection do
        post :import_csv
      end
      member do
        get :profile
        patch :profile
        get :approve_application
        post :invite
        post :invite_partner_user
        post :recertify_partner
        put :deactivate
        put :reactivate
      end
    end

    resources :partner_groups, only: [:new, :create, :edit, :update]

    resources :diaper_drives
    resources :donations do
      # collection do
      #   get :scale
      #   post :scale_intake
      # end
      patch :add_item, on: :member
      patch :remove_item, on: :member
    end

    resources :purchases
    # MODIFIED route by adding destroy to
    resources :requests, only: %i(index new show) do
      member do
        post :start
      end
    end

    resources :requests, except: %i(destroy) do
      resource :cancelation, only: [:new, :create], controller: 'requests/cancelation'
      get :print, on: :member
      collection do
        get :partner_requests
      end
    end

    get "dashboard", to: "dashboard#index"
    get "forecasting/distributions", to: "forecasting/distributions#index"
    get "forecasting/purchases", to: "forecasting/purchases#index"
    get "forecasting/donations", to: "forecasting/donations#index"
  end

  resources :attachments, only: %i(destroy)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "help", to: "help#show"
  get "pages/:name", to: "static#page"
  get "/register", to: "static#register"
  resources :account_requests, only: [:new, :create] do
    collection do
      get 'confirmation'
      get 'confirm'
      get 'received'

      get 'invalid_token'
    end
  end

  root "static#index"
end

app/models/partners/faq.rb
module Partners
  class Faq < Base
    belongs_to :partner
  end
end

app/controllers/partners/faqs_controller.rb
module Partners
  class FaqsController < BaseController
    layout 'partners/application'

    def index
      @current_partner_faqs = current_partner.faqs
    end
  
    def create
      @partner_faq = Partners::Faq.new(partner_faq_params)
      if @partner_faq.save
        redirect_to partners_faqs_path, notice: "FAQ successfully added"
      else
        redirect_to partners_faqs_path, error: "FAQ creation did not succeed; please try again"
      end
    end
  
    def destroy
      if current_partner.faqs.find(params[:id]).destroy
        redirect_to partner_faqs_path, notice: "FAQ successfully deleted"
      else
        redirect_to partner_faqs_path, notice: "Deleting the FAQ did not succeed; please try again"
      end
    end
  
    def new
      @partner_faq = Partners::Faq.new
    end
  
    private
  
    def partner_faq_params
      params.require(:partners_faq).permit(:partner_id, :question, :answer)
    end
  end
end

app/controllers/partners/helps_controller.rb
module Partners
  class HelpsController < BaseController
    layout 'partners/application'

    def show; end
  end
end

app/controllers/partners/invitations_controller.rb
# This exists so that we can override some of the devise resource
class Partners::InvitationsController < Devise::InvitationsController
  layout "devise_partner_users"

  skip_before_action :redirect_to_human_essentials
  skip_before_action :authorize_user
  skip_before_action :authenticate_user!
  # This one causes a redirect require_no_authentication
  skip_before_action :require_no_authentication

  #
  # This update action was added to override and add new redirection behaviors
  # when accepting an invitation. Namely, we want do not want to redirect
  # newly invited users to the unfinished version of partnerbase within
  # this repo. Instead we'll want to redirect them to the legacy partnerbase
  # application until we are ready.
  #
  # **Once we've migrated all users to partnerbase within this repo,
  # we can erase this file entirely**
  #
  # Here is a reference of the original endpoint code that that was modified
  # https://github.com/scambra/devise_invitable/blob/f6a308d427de1bd263337be4a334f586962ce589/app/controllers/devise/invitations_controller.rb#L45-L68
  #
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    # The self.resource is a partner_user record
    self.resource = accept_resource
    invitation_accepted = resource.errors.empty?

    yield resource if block_given?

    if invitation_accepted
      if redirect_to_legacy_partnerbase_app?
        # Redirect to the legacy partnerbase login url outside of development
        # to avoid them from going to the unfinished partnerbase in the repo.
        redirect_to legacy_partnerbase_login_url
      elsif resource.class.allow_insecure_sign_in_after_accept
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message if is_flashing_format?
        resource.after_database_authentication
        sign_in(resource_name, resource)
        respond_with resource, location: after_accept_path_for(resource)
      else
        set_flash_message :notice, :updated_not_active if is_flashing_format?
        respond_with resource, location: new_session_path(resource_name)
      end
    else
      resource.invitation_token = raw_invitation_token
      respond_with_navigational(resource) { render :edit }
    end
  end

  private

  def redirect_to_legacy_partnerbase_app?
    !Rails.env.development?
  end

  def legacy_partnerbase_login_url
    ENV.fetch("PARTNER_BASE_URL") + "/users/sign_in"
  end
end

app/controllers/partners/requests/pickup_sheets_controller.rb
module Partners
  module Requests
    class PickupSheetsController < BaseController

      def show
        @partner_request = current_partner.requests.find(params[:request_id])
        @child_item_requests = @partner_request.child_item_requests
      end
    end
  end
end

app/controllers/partners/requests_controller.rb
module Partners
  class RequestsController < BaseController
    layout 'partners/application'

    protect_from_forgery with: :exception

    def index
      @partner = current_partner
      @partner_requests = @partner.requests.includes(:child_item_requests).order(created_at: :desc).limit(10)
    end

    def new
      @partner_request = Partners::Request.new
      @partner_request.item_requests.build

      # Fetch the valid items
      @requestable_items = Organization.find(current_partner.diaper_bank_id).valid_items.map do |item|
        [item[:name], item[:id]]
      end.sort
    end

    def show
      @partner_request = current_partner.requests.find(params[:id])
    end

    def create
      create_service = Partners::RequestCreateService.new(
        partner_user_id: current_partner_user.id,
        comments: partner_request_params[:comments],
        item_requests_attributes: partner_request_params[:item_requests_attributes]&.values || []
      )

      create_service.call
      if create_service.errors.none?
        redirect_to partner_user_root_path, notice: "Request was successfully created."
      else
        @partner_request = create_service.partner_request
        @errors = create_service.errors
        @requestable_items = Organization.find(current_partner.diaper_bank_id).valid_items.map do |item|
          [item[:name], item[:id]]
        end.sort

        render :new
      end
    end

    private

    def partner_request_params
      params.require(:partners_request).permit(:comments, item_requests_attributes: [
                                                 :item_id,
                                                 :quantity,
                                                 :_destroy
                                               ])
    end
  end
end

app/controllers/partners_controller.rb
# Provides full CRUD for Partners. These are minimal representations of corresponding Partner records in PartnerBase.
# Though the functionality of Partners is actually fleshed out in PartnerBase, in DiaperBase, we maintain a collection
# of which Partners are associated with which Diaperbanks.
class PartnersController < ApplicationController
  include Importable

  def index
    @unfiltered_partners_for_statuses = Partner.where(organization: current_organization)
    @partners = Partner.includes(:partner_group).where(organization: current_organization).class_filter(filter_params).alphabetized
    @partner_groups = PartnerGroup.includes(:partners, :item_categories).where(organization: current_organization)

    respond_to do |format|
      format.html
      format.csv { send_data Partner.generate_csv(@partners), filename: "Partners-#{Time.zone.today}.csv" }
    end
  end

  def create
    svc = PartnerCreateService.new(organization: current_organization, partner_attrs: partner_params)
    svc.call

    @partner = svc.partner

    if svc.errors.none?
      redirect_to partners_path, notice: "Partner #{@partner.name} added!"
    else
      flash[:error] = "Failed to add partner due to: #{svc.errors.full_messages}"
      render action: :new
    end
  end

  def approve_application
    @partner = current_organization.partners.find(params[:id])

    svc = PartnerApprovalService.new(partner: @partner)
    svc.call

    if svc.errors.none?
      redirect_to partners_path, notice: "Partner approved!"
    else
      redirect_to partners_path, error: "Failed to approve partner because: #{svc.errors.full_messages}"
    end
  end

  def show
    @partner = current_organization.partners.find(params[:id])
    @impact_metrics = @partner.profile.impact_metrics unless @partner.uninvited?
    @partner_distributions = @partner.distributions.order(created_at: :desc)
    @partner_profile_fields = current_organization.partner_form_fields

    respond_to do |format|
      format.html
      format.csv do
        send_data Exports::ExportDistributionsCSVService.new(distribution_ids: @partner_distributions.map(&:id)).generate_csv, filename: "PartnerDistributions-#{Time.zone.today}.csv"
      end
    end
  end

  def new
    @partner = current_organization.partners.new
    @partner_groups = current_organization.partner_groups
  end

  def edit
    @partner = current_organization.partners.find(params[:id])
    @partner_groups = PartnerGroup.where(organization: current_organization)
  end

  def update
    @partner = current_organization.partners.find(params[:id])
    if @partner.update(partner_params)
      redirect_to partner_path(@partner), notice: "#{@partner.name} updated!"
    else
      flash[:error] = "Something didn't work quite right -- try again?"
      render action: :edit
    end
  end

  def destroy
    current_organization.partners.find(params[:id]).destroy
    redirect_to partners_path
  end

  def invite
    partner = current_organization.partners.find(params[:id])

    svc = PartnerInviteService.new(partner: partner)
    svc.call

    if svc.errors.none?
      redirect_to partners_path, notice: "Partner #{partner.name} invited!"
    else
      redirect_to partners_path, notice: "Failed to invite #{partner.name}! #{svc.errors.full_messages}"
    end
  end

  def invite_partner_user
    partner = current_organization.partners.find(params[:partner])
    existing_partner_user = PartnerUser.find_by(email: params[:email], partner: partner.profile)
    if existing_partner_user
      existing_partner_user.invite!
    else
      PartnerUser.invite!(email: params[:email], partner: partner.profile)
    end

    redirect_to partner_path(partner), notice: "We have invited #{params[:email]} to #{partner.name}!"
  rescue StandardError => e
    redirect_to partner_path(partner), error: "Failed to invite #{params[:email]} to #{partner.name} due to: #{e.message}"
  end

  def recertify_partner
    @partner = current_organization.partners.find(params[:id])

    svc = PartnerRequestRecertificationService.new(partner: @partner)
    svc.call

    if svc.errors.none?
      flash[:success] = "#{@partner.name} recertification successfully requested!"
    else
      flash[:error] = "#{@partner.name} failed to update partner records"
    end

    redirect_to partners_path
  end

  def deactivate
    @partner = current_organization.partners.find(params[:id])

    svc = PartnerDeactivateService.new(partner: @partner)
    svc.call

    if svc.errors.none?
      redirect_to partners_path, notice: "#{@partner.name} successfully deactivated!"
    else
      redirect_to partners_path, error: "#{@partner.name} failed to deactivate due to: #{svc.errors.full_messages}"
    end
  end

  def reactivate
    @partner = current_organization.partners.find(params[:id])

    if @partner.status != "deactivated"
      redirect_to(partners_path, error: "#{@partner.name} is not deactivated!") && return
    end

    svc = PartnerReactivateService.new(partner: @partner)
    svc.call

    if svc.errors.none?
      redirect_to partners_path, notice: "#{@partner.name} successfully reactivated!"
    else
      redirect_to partners_path, error: "#{@partner.name} failed to reactivate due to: #{svc.errors.full_messages}"
    end
  end

  private

  def partner_params
    params.require(:partner).permit(:name, :email, :send_reminders, :quota, :notes, :partner_group_id, 
                                    documents: [],
                                    faqs_attributes: [:id, :question, :answer, :_destroy])
  end

  helper_method \
    def filter_params
    return {} unless params.key?(:filters)

    params.require(:filters).permit(:by_status)
  end
end

app/views/partners/requests/_error.html.erb
<div class='bg-red-200 p-3 mb-10 animate-pulse-once flex flex-col sm:flex-row items-center rounded text-center'>
  <div class='p-4 text-red-500'>
    <svg xmlns="http://www.w3.org/2000/svg" width="150" height="150" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
  </div>
  <div class='text-red-600 md:text-left'>
    <h3 class='text-4xl font-extrabold'>Opps! Something went wrong with your Request</h3>
    <p class='text-lg font-bold'>
      Ensure each line item has a item selected AND a quantity greater than 0.
    </p>
    <p class='text-md'>
      Still need help? Submit a support ticket <%= link_to 'here', support_ticket_form_url, target: '_blank' %> and we will do our best to follow up with you via email.
    </p>
  </div>
</div>

app/views/partners/requests/_history.html.erb
<div class="card mb-4">
  <h5 class="card-header bg-info">Essentials Request History</h5>
  <div class="card-body">
    <div class=container-fluid>
      <div class="row justify-content-around">
        <div class="col-6-lg">
          <h2>Your recent essentials requests</h2>
        </div>
        <div class="col-6-lg">
        </div>
      </div>
      <table class="table table-striped dashboard">
        <thead>
          <tr class="row">
            <th scope="col" class="col-1">No.</th>
            <th scope="col" class="col-6">Contents</th>
            <th scope="col" class="col text-right">Edit Pickup Sheet</th>
            <th scope="col" class="col">Request Date</th>
          </tr>
        </thead>

        <tbody>
          <% @partner_requests.each do |partner_request| %>
            <tr class="row">
              <td class="col-1"><%= link_to partner_request.id, partners_request_path(id: partner_request.id) %></th>
              <td class="col-6"><%= partner_request.item_requests.map {|item| "#{item.quantity} of #{item.name}"}.join(", ") %></td>
              <td class="col text-right">
                <% if partner_request.child_item_requests.any? %>
                  <%= link_to '<i class="fa fa-edit"></i>&nbsp;&nbsp;Pickup Sheet'.html_safe, partners_request_pickup_sheet_path(request_id: partner_request.id), class: 'btn btn-sm btn-primary' %><
                <% end %>
              </td>
              <td class="col"><%= partner_request.created_at.strftime("%B %-d %Y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/partners/requests/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Essentials Requests - #{current_partner_user.name}" %>
        <h1><i class="fa fa-edit"></i>&nbsp;&nbsp;Essentials Requests
          <small>for <%= current_partner_user.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(partner_user_root_path) do %>
              <i class="fa fa-dashboard"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item">
            <a><%= "#{current_partner.name}" %></a></li>
          <li class="breadcrumb-item"><a href="#">Essentials Requests</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>


<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- Default box -->
        <%= render 'request_options_card' if @partner.verified? %>

        <div class="card">
          <div class="card-header bg-info">
            <h1 class="card-title">Request History</h1>
          </div>
          <div class="card-body p-0">

            <table class="table">
              <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Contents</th>
                <th scope="col">Pickup Sheet</th>
                <th scope="col">Request Date</th>
              </tr>
              </thead>
              <tbody>
              <% @partner_requests.each do |partner_request| %>
                <tr>
                  <th scope="row"><%= link_to partner_request.id, partners_request_path(id: partner_request.id) %></th>
                  <td><%= partner_request.item_requests.map { |item| "#{item.quantity} of #{item.name}" }.join(", ") %></td>
                  <td>
                    <% if partner_request.child_item_requests.any? %>
                      <%= link_to partners_request_pickup_sheet_path(request_id: partner_request.id), class: 'btn btn-sm btn-info' do %>
                        <i class="fa fa-edit"></i> Pickup Sheet
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= partner_request.created_at.strftime("%B %-d %Y") %></td>
                </tr>
                </tbody>
              <% end %>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>