config/routes.rb
def set_up_sidekiq
  require 'sidekiq/web'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      compare = ->(s1, s2) { ActiveSupport::SecurityUtils.secure_compare(s1, s2) }
      compare.call(username, ENV["SIDEKIQ_USERNAME"]) && compare.call(password, ENV["SIDEKIQ_PASSWORD"])
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

def set_up_flipper
  flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
    builder.use Rack::Auth::Basic do |username, password|
      username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
    end
  end
  mount flipper_app, at: "/flipper"
end

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_for :partner_users, controllers: { sessions: "partners/sessions", invitations: 'partners/invitations', passwords: 'partners/passwords' }
  resources :logins, only: [:new, :create], controller: "consolidated_logins"

  set_up_sidekiq
  set_up_flipper

  # Add route partners/dashboard so that we can define it as partner_user_root
  get 'partners/dashboard' => 'partners/dashboards#show', as: :partner_user_root
  namespace :partners do
    resource :dashboard, only: [:show]
    resource :help, only: [:show]
    resources :requests, only: [:show, :new, :index, :create]
    resources :individuals_requests, only: [:new, :create]
    resources :family_requests, only: [:new, :create]
    resources :users, only: [:index, :new, :create]
    resource :profile, only: [:show, :edit, :update]
    resource :approval_request, only: [:create]

    resources :children, except: [:destroy] do
      post :active
    end
    resources :families
    resources :authorized_family_members
  end

  # This is where a superadmin CRUDs all the things
  get :admin, to: "admin#dashboard"
  namespace :admin do
    get :dashboard
    resources :base_items
    resources :organizations
    resources :partners, except: %i[new create destroy]
    resources :users
    resources :barcode_items
    resources :account_requests, only: [:index]
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  scope path: ":organization_id" do
    resources :users

    # Users that are organization admins can manage the organization itself
    resource :organization, only: [:show]
    resource :organization, path: :manage, only: %i(edit update) do
      collection do
        post :invite_user
        put :deactivate_user
        put :reactivate_user
        post :resend_user_invitation
        post :promote_to_org_admin
        post :demote_to_user
      end
    end

    resources :adjustments, except: %i(edit update)
    resources :audits do
      post :finalize
    end

    namespace :reports do
      resources :ndbn_annuals, only: [:index, :show], param: :year
    end

    resources :transfers, only: %i(index create new show destroy)
    resources :storage_locations do
      collection do
        post :import_csv
        post :import_inventory
      end
      member do
        get :inventory
      end
    end

    resources :distributions do
      get :print, on: :member
      collection do
        get :schedule
        get :pickup_day
      end
      patch :picked_up, on: :member
    end

    resources :barcode_items do
      get :find, on: :collection
      get :font, on: :collection
    end
    resources :donation_sites do
      collection do
        post :import_csv
      end
    end
    resources :diaper_drive_participants, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :manufacturers, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :vendors, except: [:destroy] do
      collection do
        post :import_csv
      end
    end
    resources :kits do
      member do
        get :allocations
        post :allocate
      end
    end

    resources :profiles, only: %i(edit update)
    resources :items do
      patch :restore, on: :member
    end
    resources :item_categories
    resources :partners do
      collection do
        post :import_csv
      end
      member do
        get :profile
        patch :profile
        get :approve_application
        post :invite
        post :invite_partner_user
        post :recertify_partner
        put :deactivate
        put :reactivate
      end
    end

    resources :partner_groups, only: [:new, :create, :edit, :update]

    resources :diaper_drives
    resources :donations do
      # collection do
      #   get :scale
      #   post :scale_intake
      # end
      patch :add_item, on: :member
      patch :remove_item, on: :member
    end

    resources :purchases
    # MODIFIED route by adding destroy to
    resources :requests, only: %i(index new show) do
      member do
        post :start
      end
    end

    resources :requests, except: %i(destroy) do
      resource :cancelation, only: [:new, :create], controller: 'requests/cancelation'
      get :print, on: :member
      collection do
        get :partner_requests
      end
    end

    get "dashboard", to: "dashboard#index"
    get "forecasting/distributions", to: "forecasting/distributions#index"
    get "forecasting/purchases", to: "forecasting/purchases#index"
    get "forecasting/donations", to: "forecasting/donations#index"
  end

  resources :attachments, only: %i(destroy)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "help", to: "help#show"
  get "pages/:name", to: "static#page"
  get "/register", to: "static#register"
  resources :account_requests, only: [:new, :create] do
    collection do
      get 'confirmation'
      get 'confirm'
      get 'received'

      get 'invalid_token'
    end
  end

  root "static#index"
end

app/views/layouts/_devise_shared.html.erb
<%# required params: title, body_class, masthead_img_src   %>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><%= title %></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_pack_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  <style>
    .checkbox label{
      padding-left: 0px;
    }
  </style>
  <script>
    $(document).ready(function() {
      <% if Rails.env.staging? %>
        // Prevents users from closing the modal by clicking outside of it or pressing the esc key
        $('#warningModal').modal({
          backdrop: 'static',
          keyboard: false
        });
        // Adds click event handler on the checkbox
        $('#defaultCheck1').click(function(){
          // If the checkbox is checked, enable the continue button
          if($(this).is(':checked')){
            $('.continue-btn').attr("disabled", false);
          } else{
            $('.continue-btn').attr("disabled", true);
          }
        });
      <% end %>
    });
  </script>
</head>

<body id="devise" class="hold-transition login-page <%= body_class %> <%= Rails.env.staging? ? 'login-page-test' : '' %>">
  <div class="login-box">
    <% if masthead_img_src %>
      <div class="login-logo text-center">
        <img id="MastheadLogo" src=<%= masthead_img_src %> alt="Human Essentials" title="Human Essentials" class="serv_icon"/>
      </div>
    <% end %>

    <!-- /.login-logo -->
    <div class="login-box-body">
      <div class="form-group has-feedback">
        <%= yield %>
      </div>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- Modal -->
  <div class="modal fade" id="warningModal" tabindex="-1" role="dialog" aria-labelledby="warningModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="warningModalLabel"><b>This site is for TEST purposes only!</b></h3>
        </div>
        <div class="modal-body">
          You're visiting diaperbase.org, a demo/test site for the full site at <a href="https://diaper.app">diaper.app</a>.<br>
          It is not safe to upload, enter or save any sensitive data here.<br>
          <div class="modal-body-warning-text">
            If you meant to login to your live account, go to <a href="https://diaper.app/users/sign_in">diaper.app</a>
          </div>
          <br>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
            <label class="form-check-label" for="defaultCheck1">
              I Understand
            </label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-warning continue-btn" data-dismiss="modal" disabled>Continue To The Test Site</button>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/_lte_navbar.html.erb
<% if current_user.super_admin? %>
<li class="nav-item dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#">
    <i class="fa fa-lock"></i> Administration
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= navigation_link_to "Dashboard", admin_dashboard_path %>
    </li>
    <li>
      <%= navigation_link_to "Organizations", admin_organizations_path %>
    </li>
    <li>
      <%= navigation_link_to "Base items", admin_base_items_path %>
    </li>
    <li>
      <%= navigation_link_to "Users", admin_users_path %>
    </li>
  </ul>
</li>
<% end %>

<li class="nav-item dropdown">
  <%= link_to 'Need Help?', organization_faq_index_path, class: 'nav-link' %>
</li>

<li class="nav-item dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#">
    <i class="fa fa-calendar"></i>
    <span class="badge badge-danger navbar-badge" style="background-color: #007bff"><%= current_organization.distributions.upcoming.count.to_s.gsub(/^0$/, '') %></span>
  </a>
  <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
    <a href="#" class="dropdown-item">
      <i class="fas fa-file mr-2"></i> <%= current_organization.distributions.upcoming.count %> Pick-ups
      remaining this week
    </a>
    <div class="dropdown-divider"></div>
    <%= link_to_if current_organization.id.present?, "View Calendar", schedule_distributions_path(organization_id: current_organization.to_param), class: "dropdown-item dropdown-footer" %>
  </div>
</li>

<li class="nav-item dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#">
    <i class="fa fa-bell-o"></i>
    <% if current_organization && (current_organization.requests.status_pending.size > 0 || current_organization.partners.awaiting_review.size > 0) %>
    <span class="badge badge-warning navbar-badge" style="background-color: #ffc107"><%= (current_organization.requests.status_pending.size + current_organization.partners.awaiting_review.size) %></span>
    <% end %>
  </a>
  <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
    <%= link_to(requests_path, class: "dropdown-item") do %>
    <i class="fa fa-file-text text-aqua"></i> <%= current_organization&.requests.status_pending.size rescue "0" %>
    Diaper Requests
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to(partners_path, class: "dropdown-item") do %>
    <i class="fa fa-file-text text-aqua"></i> <%= current_organization&.partners.awaiting_review.size rescue "0" %>
    Partner Agencies Pending Review
    <% end %>
  </div>
</li>

<li class="nav-item dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#">
    <%= current_user.name %>
  </a>
  <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
    <%= link_to edit_user_registration_path(organization_id: nil), class:"dropdown-item" do %>
    <i class="fa fa-cog text-aqua"></i> Account Settings
    <% end %>
    <% if current_organization.id.present? &&
        (current_user.super_admin? ||
            (current_user.organization_admin? &&
                current_organization.id == current_user.organization_id)) %>
    <% with_options organization_id: current_user.organization.to_param do |with_org| %>

    <div class="dropdown-divider"></div>
    <%= link_to with_org.users_path, class:"dropdown-item" do %>
    <i class="fas fa-users mr-2"></i> My Co-Workers
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to with_org.organization_path, class:"dropdown-item" do %>
    <i class="fas fa-sitemap mr-2"></i> My Organization
    <% end %>
    <% end %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to destroy_user_session_path(organization_id: nil), class:"dropdown-item dropdown-footer", method: :delete do %>
    <i class="fa fa-sign-out mr-2"></i> Log Out
    <% end %>
  </div>
</li>

app/views/layouts/devise.html.erb
<%= render(
  'layouts/devise_shared',
  title: 'Human Essentials | Bank | Log in',
  body_class: 'login-page--user',
  masthead_img_src: "/img/essentials.svg"
)%>

app/views/layouts/devise_consolidated_login.html.erb
<%= render(
  'layouts/devise_shared',
  title: 'Human Essentials | Log in',
  body_class: 'login-page--consolidated',
  masthead_img_src: nil
)%>

app/views/layouts/devise_partner_users.html.erb
<%= render(
  'layouts/devise_shared',
  title: 'Human Essentials | Partner | Log in',
  body_class: 'login-page--partner',
  masthead_img_src: "/img/partnerbase-logo.svg"
)%>

app/views/layouts/view_component_previews.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>View Component Previews</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <%= render 'magic_test/support' if Rails.env.test? %>
  </head>

  <body class='pt-5'>
    <%= yield %>
  </body>
</html>